Program ::= Expr
Expr    ::= NExpr
          | BExpr
NExpr   ::= Const
          | Diff
Const   ::= Number
Diff    ::= '-' '(' NExpr ',' NExpr ')'
BExpr   ::= Zero
Zero    ::= 'zero?' '(' NExpr ')'
Number  ::= [0-9]+

/* Use https://www.bottlecaps.de/rr/ui to view it as a Railroad Diagram. */
